# Generated by Django 5.1.2 on 2024-11-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
