# Generated by Django 5.0.7 on 2024-08-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Адрес не указан', max_length=255, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Телефон не указан', max_length=15, verbose_name='Телефон получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='Получатель не указан', max_length=100, verbose_name='Имя получателя'),
        ),
    ]
