# Generated by Django 5.1.3 on 2024-11-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='1111-11-11', max_length=20),
            preserve_default=False,
        ),
    ]
