# Generated by Django 5.1.3 on 2024-11-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comment',
            new_name='user_comment',
        ),
    ]
