# Generated by Django 5.0.6 on 2024-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_commentary_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commentary',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_place',
            field=models.TextField(default=None),
        ),
    ]
