# Generated by Django 5.0.6 on 2024-09-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_commentary_alter_order_delivery_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commentary',
            field=models.TextField(blank=True, default='Комментарий', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_place',
            field=models.TextField(default='Адрес доставки'),
        ),
    ]
