# Generated by Django 5.0.6 on 2024-09-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_commentary_alter_order_delivery_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_place',
            field=models.TextField(blank=True, default='Адрес доставки', null=True),
        ),
    ]
