# Generated by Django 5.1.3 on 2024-11-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manageorder',
            old_name='user_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='manageorder',
            old_name='user_surname',
            new_name='last_name',
        ),
    ]
