# Generated by Django 5.1.3 on 2024-11-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0002_rename_user_name_manageorder_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageorder',
            name='comment',
        ),
        migrations.AddField(
            model_name='manageorder',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
