# Generated by Django 5.1.3 on 2024-12-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders', '0004_manageorder_user_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manageorder',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
