# Generated by Django 5.1.2 on 2024-10-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
