# Generated by Django 5.1.2 on 2024-11-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
    ]
